fetch:
  url: "https://raw.githubusercontent.com/WeThinkGG/curesword/refs/heads/main/gg.txt"  # URL to fetch the blacklist/whitelist from
  interval: 3600  # Time interval in seconds to refetch the list (3600 seconds = 1 hour)
  
# Cleans up whitelisted expressions from the message
# This is basically a bypass for certain patterns
whitelist:
  enabled: true

general:
  # If enabled, other checks will ignore non-latin characters to improve detection.
  sanitize: true

  # If enabled, other checks will ignore player names to improve detection.
  sanitize-names: true

  # Filter and remove non-latin characters from all messages.
  filter-other: false

  # Commands that will be treated as normal messages
  commands:
    - /broadcast
    - /ebroadcast
    - /bc
    - /ebc
    - /tell
    - /etell
    - /msg
    - /emsg
    - /reply
    - /ereply
    - /r
    - /er
    - /global
    - /g

# Checks if the player is using blacklisted words.
blacklist:
  enabled: true
  fetch-from-url: true  # Fetch blacklist from URL enabled

  # Show a fake message to the player to make him think his message was sent.
  fake_message: false

  # Hide the words the player wrote with a ***
  censorship:
    enabled: true
    replacement: "***"

  warn:
    max: 3
    notification: "&b&lCSP: &e%player% &ffailed &6Swearing &7(&c%message%&7)"

  punishments:
    - "mute -s %player% Offensive Language (%message%) 1d"
  
  block_raw_message: true

# Checks if messages have too many caps.
caps:
  enabled: true
  replace: true
  max: 8

  warn:
    max: -1
    notification: "&b&lCSP: &e%player% &ffailed &6Caps &7(&c%message%&7)"

  punishments: []

# Checks if player is chatting too fast.
cooldown:
  enabled: true
  time:
    repeat-global: 1000
    repeat: 10000
    normal: 1000
    command: 400

# Checks if player is using too many repeated characters.
flood:
  enabled: true
  replace: true
  pattern: (\w)\1{5,}|(\w{28,})|([^\wñ]{20,})|(^.{220,}$)

  warn:
    max: -1
    notification: "&b&lCSP: &e%player% &ffailed &6Flood &7(&c%message%&7)"

  punishments: []

# Checks if the player is using syntax.
syntax:
  enabled: true
  whitelist:
    - "/chatsenttinel:"

  warn:
    max: -1
    notification: "&b&lCSP: &e%player% &ffailed &6Syntax &7(&c%message%&7)"

  punishments: []
