name: Build and Upload Minecraft Plugin

on:
  push:
    branches:
      - master  # Specify the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the version of Java required by Minecraft plugin

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Upload JAR as an artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: target/*.jar  # The JAR file is usually located in the 'target' directory

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Create GitHub release with the JAR file
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Release of version ${{ github.ref_name }}"
          files: target/*.jar  # Adjust the path if the JAR is in a different location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
