name: Build and Upload Minecraft Plugin

on:
  push:
    branches:
      - master  # Trigger workflow on push to master
    tags:
      - 'v*'  # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: maven

      # Step 3: Ensure target directory exists
      - name: Ensure target directory exists
        run: |
          if [ ! -d "target" ]; then
            mkdir target
          fi

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Upload JAR as an artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: plugin-jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only run for tags

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create GitHub release and upload JAR
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Tag as the version name
          release_name: "Release ${{ github.ref_name }}"  # Create a release with the tag name
          body: "Release of version ${{ github.ref_name }}"  # Set the release description
          files: target/*.jar  # Upload the built JAR file to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
